// export const HandleError = async (promises) => {
//   try {
//     const data = await promises;
//     return [data, null];
//   } catch (error) {
//     return [null, error];
//   }
// };

